### ISSUE TITLE
Why the opening mode of the file is 'wb'?

### ISSUE THREAD

**Issue by emanuelgauler** [felixbuenemann/xlsxtream#33]
I suggest that the opening mode can be determined by the user, because when I want to modify an existing file, it is truncated.

**Comment by felixbuenemann** [comment]
XLSX files are ZIP archives with binary data.

There's no way to append to it anyways, so I'm not sure what you are trying to achieve.

By the way you can pass an open IO-like object to `Xlsxtream::Workbook.new` or `.open`, so you can open a file in whichever mode you like.
