### ISSUE TITLE
zip_tricks update

### ISSUE THREAD

**Issue by skcc321** [felixbuenemann/xlsxtream#37]
Hi there. I see that there is newer version of zip_tricks (newest 5.0.0, installed 4.8.0).
Could you please update dependencies. Thank you

**Comment by felixbuenemann** [comment]
Master now supports zip_tricks 5.x, I'll release a new version shortly.

**Comment by felixbuenemann** [comment]
I've released [xlsxtream v2.2.0](https://rubygems.org/gems/xlsxtream/versions/2.2.0) on RubyGems.
