### ISSUE TITLE
Storing numeric strings as numbers

### ISSUE THREAD

**Issue by sandstrom** [felixbuenemann/xlsxtream#7]
I've noticed that Excel shows a warning if numeric strings (strings with only numeric characters) are present in a spreadsheet.

![screen shot 2017-09-07 at 16 56 51](https://user-images.githubusercontent.com/122287/30169828-c35196f8-93ed-11e7-865b-d9d0e8e65604.png)

I think the fix is fairly straightforward. Basically something like this (I haven't checked that this code works, just to illustrate the idea)

```ruby
if value.is_a?(String) && value =~ /\A[\d\.]+/z/
  # add as a value
else
  # current handling of strings…
end
```

Would you be willing to add functionality along these lines? Either by default or behind an option (opt-in or opt-out).

**Comment by felixbuenemann** [comment]
Could you describe your use case?

Checking every string value against a regex has some overhead and Xlsxstream tries to be as efficient as possible.

Is there a reason you can't just convert the columns to a ruby number before passing them into row?

I'm not against this feature, but it should probably be implemented with an opt-in option that enables automatic type detection for numbers, dates and times.

**Comment by sandstrom** [comment]
**Use case**
For some of our columns the values may be strings in one export and numbers in another. It is correct that this can also be handled in the consuming application instead of the gem/library.

**Rationale**
As a gem-user I'd like to simply drop data into Xlsxstream and have it produce a good XLSX-file. Since Excel shows the warning above, it would be neat if Xlsxstream could "do the right thing" and make Excel happy.

If this conversion happens in the consuming application one needs to know about the intricacies of XSLX and Excel. I happen to know this now, but I had to spend an hour tracking down this problem. Better if we could safe others the pain. Doing it in the library also feels like the right place to tackle this.

Opt-in sounds alright, I agree with the perf argument.

Let me know what you think!

## Number

How about this for number? `/\A-?[0-9]+(\.[0-9]+)?\z/`

Some strings that matches:
894
923.21
0.32
-894
-923.21
-0.32

Some that don't:

hello
9bye
888,323
5,434.3
-8,336.09
87078.
.123

## Date

I'd say we'd only support ISO 8601. Ruby's `Time` already has a parser so `Time.iso8601(str)` can do most of the heavy lifting.

We'd simply have to separate dates from times and for this the standard `yyyy-mm-dd` and `yyyy-mm-ddThh:mm:ss` separation should do the job.

**Comment by felixbuenemann** [comment]
Your proposal sounds good.

Would you like to try implementing it yourself and making a PR?

You could add a new option like `auto_format: true` to `Xlsxtream::Workbook#write_worksheet` to toggle the format parsing.

I'm very busy currently, so I can't take care of implementing it myself right now.

**Comment by sandstrom** [comment]
Sounds good! I'll make a stab at it, should have a PR ready within the next 3-4 days.

**Comment by felixbuenemann** [comment]
Btw. in order to avoid overhead and excessive object allocation, move the detection regexes into constants and freeze them, it makes a big performance difference when the regex is checked in a loop.
