### ISSUE TITLE
Control characters break xlsx generation

### ISSUE THREAD

**Issue by jbwl** [felixbuenemann/xlsxtream#9]
Hi Felix, thank you for this gem, it works well. I found out that having control characters in my model's attributes (e.g. varchars with dirty user input etc.) will break the xlsx generation. The xlsx file will "end" at the first control character.

I was able to work around it by using `.strip` on all strings I add to the sheet. Maybe there is a more elegant solution?

**Comment by felixbuenemann** [comment]
Could you provide a more concrete example of what inputs where causing trouble?

You could call `#inspect` and `#encoding` on the dirty strings, to see what special character they contain.

Currently Xlsxtream asumes the content is UTF8 or tries to convert it to UTF8 otherwise.

If you have user provides content you could use Ruby's built-in `String#scrub`method to clean the data before passing it on to the gem, if the input contains invalid codepoints.

Theoretically newlines and other whitespace characters shouldn't be an issue, which is what `String#strip` would remove.

**Comment by jbwl** [comment]
In this case the string contained a tab \\t character. 
This didn't break the loop where I added the rows to the sheet - it went through all 500 items in my data array with no errors or exceptions raised.

But when opening the .xlsx (with Libre Office or Numbers, sorry I don't have MS-Excel), I found that no cells after the one with the tab character were written, and no empty lines either.

**Comment by felixbuenemann** [comment]
I'll have to check the SpreadsheetML spec, maybe certain control characters are forbidden.

**Comment by felixbuenemann** [comment]
OK, looks like inline String are of type `ST_Xstring` which require escaping certain characters as hex in the form of `_xHHHH_`, so for example `\t` would be encoded as `_x0009_`.

More details taken from [this stackoverflow answer](https://stackoverflow.com/questions/43094662/excel-accepts-some-characters-whereas-openxml-has-error/43141040#43141040):

> The possible values for this element are defined by the ST_Xstring simple type (§22.9.2.19).

> 22.9.2.19 ST_Xstring (Escaped String)
String of characters with support for escaped invalid-XML characters. For all characters which cannot be represented in XML as defined by the XML 1.0 specification, the characters are escaped using the Unicode numerical character representation escape character format xHHHH, where H represents a hexadecimal character in the character's value. [Example: The Unicode character 8 is not permitted in an XML 1.0 document, so it must be escaped as x0008. end example]

**Comment by felixbuenemann** [comment]
So this is a bug in xlsxtream and should be fixed.

**Comment by felixbuenemann** [comment]
I found some more info on [valid characters in XML 1.0](http://www.sklar.com/archives/96-XML-vs.-Control-Characters.html):

> The XML spec says that in XML documents, “Legal characters are tab, carriage return, line feed, and the legal characters of Unicode and ISO/IEC 10646.” That is:
> > Char ::= #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]

So according to this info `\t`, `\r` and `\n` should not require escaping.

@jbwl Could you post an `#inspect` and `#codepoints` output from the problematic string?

**Comment by sandstrom** [comment]
friendly ping @jbwl 😄

**Comment by felixbuenemann** [comment]
@jbwl I have just released xlsxtream 0.3.1 which implements escaping of invalid XML 1.0 characters.

**Comment by jbwl** [comment]
Thank you!

**Comment by felixbuenemann** [comment]
Btw. there was an escaping bug in 0.3.1, so you should upgrade to 1.3.2 which has the bugfix or the latest 2.0.0 version.
